# This is a basic workflow to help you get started with Actions

name: Update_DB

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: '*/5 * * * *'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
          - name: checkout repo content
            uses: actions/checkout@v3 # checkout the repository content to github runner.
          - name: setup python
            uses: actions/setup-python@v3
            with:
              python-version: 3.x #install the python needed
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
          - name: execute python script skillgems # run the run.py to get the latest data
            run: |
              python skillgems_update_db.py
            working-directory: ./utility/app1
          - name: execute python script sextants # run the run.py to get the latest data
            run: |
              python sextants_update_db.py
            working-directory: ./utility/app2
          - name: Commit and Push Changes
            run: |
              git config user.name "grummble-ai"
              git config user.email "73717764+grummble-ai@users.noreply.github.com"
              git add -u
              git commit -m "Updated with GitHub Actions" || echo "Commit didn't work"
              git push origin main || echo "Pushing didn't work"
